### ISSUE TITLE
Erreur quand ajout de javascript dans scriptsFooter.html

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-rando-v3#1029]
L'ajout de javascript dans le fichier prévu à cet effet scriptsFooter.html occasionne l'erreur :
```
nodeserver_1  | TypeError: scriptsFooter is not iterable
nodeserver_1  |     at useExternalsScripts (/app/src/.next/server/chunks/173.js:255:12)
nodeserver_1  |     at Layout (/app/src/.next/server/pages/_app.js:837:129)
nodeserver_1  |     at Wc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
nodeserver_1  |     at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
nodeserver_1  |     at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
nodeserver_1  |     at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
nodeserver_1  |     at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
nodeserver_1  |     at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
nodeserver_1  |     at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
nodeserver_1  |     at $c (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
```
Contenu de test du fichier scriptsFooter.html :
```
<script>
  console.log("hello");
</script>
```

Testé sur la version 3.17.0.

L'ajout de scripts fonctionne sur la version 3.15.3 (non testé sur les versions intermédiaires).

**Comment by pnrma** [comment]
Je confirme que l'ajout d'un saut ligne a corrigé l'erreur.
Merci.

**Comment by dtrucs** [comment]
Corrigé depuis la version [v3.17.1](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.17.1).
