### ISSUE TITLE
Erreur à la génération du sitemap

### ISSUE THREAD

**Issue by mougetann** [GeotrekCE/Geotrek-rando-v3#1171]
Bonjour,

J'essaye de récupérer le sitemap de notre geotrek-rando-v3 pour le fournir à la search console google, et lorsque je tape l'URL https://explore-test.doubs.fr/sitemap.xml, j'obtiens une erreur dans les logs qui semble bloquer sa génération (la page tombe en timeout).
```
TypeError: Cannot read properties of undefined (reading 'length')
    at /app/src/.next/server/pages/sitemap.xml.js:62:112
    at Array.map (<anonymous>)
    at getApiContentForLanguage (/app/src/.next/server/pages/sitemap.xml.js:62:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async generateSitemap (/app/src/.next/server/pages/sitemap.xml.js:76:24)
    at async Sitemap.getInitialProps (/app/src/.next/server/pages/sitemap.xml.js:85:25)
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at Function.from (node:buffer:325:9)
    at toBuffer (/app/node_modules/next/dist/compiled/compression/index.js:22:2427)
    at ServerResponse.write (/app/node_modules/next/dist/compiled/compression/index.js:22:593)
    at Sitemap.getInitialProps (/app/src/.next/server/pages/sitemap.xml.js:87:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
Est-ce la bonne façon de procéder ? Avez-vous une idée de l'origine du problème ?

**Comment by dtrucs** [comment]
Bonjour cela est dû a un breaking change de l'API depuis la 2.104.
Ce changement a été pris en charge depuis la version [v3.20.3](https://github.com/GeotrekCE/Geotrek-rando-v3/releases/tag/v3.20.3)
