### ISSUE TITLE
[Internal Server Error] Mise à jour 3.22.0

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-rando-v3#1255]
Suite à une mise à jour de Geotrek-rando. L'application à une internal serveur erreur

```
nodeserver_1  | Error: Cannot find module 'semver'
nodeserver_1  | Require stack:
nodeserver_1  | - /app/src/.next/server/pages/_app.js
nodeserver_1  | - /app/node_modules/next/dist/server/require.js
nodeserver_1  | - /app/node_modules/next/dist/server/next-server.js
nodeserver_1  | - /app/node_modules/next/dist/server/next.js
nodeserver_1  | - /app/src/server.js
nodeserver_1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
nodeserver_1  |     at mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:23:32)
nodeserver_1  |     at Module._load (node:internal/modules/cjs/loader:1051:27)
nodeserver_1  |     at Module.require (node:internal/modules/cjs/loader:1311:19)
nodeserver_1  |     at require (node:internal/modules/helpers:179:18)
nodeserver_1  |     at 912 (/app/src/.next/server/pages/_app.js:2240:18)
nodeserver_1  |     at __webpack_require__ (/app/src/.next/server/webpack-runtime.js:25:42)
nodeserver_1  |     at 796 (/app/src/.next/server/chunks/509.js:42:64)
nodeserver_1  |     at __webpack_require__ (/app/src/.next/server/webpack-runtime.js:25:42)
nodeserver_1  |     at 2079 (/app/src/.next/server/chunks/205.js:400:82) {
nodeserver_1  |   code: 'MODULE_NOT_FOUND',
nodeserver_1  |   requireStack: [
nodeserver_1  |     '/app/src/.next/server/pages/_app.js',
nodeserver_1  |     '/app/node_modules/next/dist/server/require.js',
nodeserver_1  |     '/app/node_modules/next/dist/server/next-server.js',
nodeserver_1  |     '/app/node_modules/next/dist/server/next.js',
nodeserver_1  |     '/app/src/server.js'
nodeserver_1  |   ]
nodeserver_1  | }
```

**Comment by camillemonchicourt** [comment]
Corrigé par la 3.22.1.
Testée sur https://gtr3demo.ecrins-parcnational.fr/
